### ISSUE TITLE
Travis CI vs Wandbox.org?

### ISSUE THREAD

**Issue by KjellKod** [JeffGarland/range_by_example#1]
Hi Jeff, 

This is not an "issue" but more a question regarding the feature request mention at today's library talk (c++now2017). 

What was the proposition for using WandBox.org? Is it just to see if it runs and/or have unit tests?
Maybe a travis integration would be enough? (ref: https://docs.travis-ci.com/user/getting-started)

I'm using travis CI for my g3log library and I'd be happy to make a pull request to your repo with a similar setup if that is what was requested. 

Cheers
Kjell 

PS: Example output from [Travis CI](https://travis-ci.org/KjellKod/g3log/builds/231124192?utm_source=github_status&utm_medium=notification).  Such a _cloud CI_ run happens for every pull request to the repo.

**Comment by KjellKod** [comment]
Or was the intention more like this?: https://github.com/boost-experimental/di/blob/cpp14/README.md

**Comment by JeffGarland** [comment]
Yes — this is exactly the suggestion, thanks! Should be able to reverse engineer this….

**Comment by JeffGarland** [comment]
So we've got some examples running in Wandbox, but now that we're getting some real content here and Jeff Trull has coded a change to go more strict on warnings I think we might want to set this up.  What would we need to do to setup Travis?  I'll try to catch up with you today.

**Comment by KjellKod** [comment]
As agreed. I'll add Travis for gcc, with "catch" as unit test framework, update the CMake file to add a separate test  executable. 

Once that is reviewed and merged we can later, in other pull requests, add cloud CI for clang (Travis) and possibly for Windows too (appveyor)

**Comment by JeffGarland** [comment]
This is now setup and working -- so I'm closing the issue -- thanks for the contribution!
